#!/usr/bin/env bash
# Generate .env from GCP/Firebase using gcloud (and optionally firebase) CLI.
# Usage: ./scripts/generate-env.sh
# Requires: gcloud CLI installed and logged in (gcloud auth login)
# Optional: firebase-tools (npm i -g firebase-tools) for Firebase web config

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$ROOT_DIR/.env"

# Preserve existing NEXT_PUBLIC_FIREBASE_API_KEY if present so repeated runs
# of this script don't wipe a manually-entered Web API key.
EXISTING_API_KEY=""
if [ -f "$ENV_FILE" ]; then
  EXISTING_API_KEY=$(grep -E '^NEXT_PUBLIC_FIREBASE_API_KEY=' "$ENV_FILE" 2>/dev/null | head -1 | cut -d'=' -f2-)
fi

echo "Generating .env from GCP / Firebase CLI..."
echo ""

# --- Project ID from gcloud ---
if ! command -v gcloud &>/dev/null; then
  echo "Error: gcloud CLI not found. Install: https://cloud.google.com/sdk/docs/install"
  exit 1
fi

PROJECT_ID=$(gcloud config get-value project 2>/dev/null || true)
if [ -z "$PROJECT_ID" ]; then
  echo "Error: No GCP project set. Run: gcloud config set project YOUR_PROJECT_ID"
  exit 1
fi

echo "Using GCP project: $PROJECT_ID"

# --- GCS bucket (default name) ---
GCS_BUCKET="${PROJECT_ID}-blog-images"
echo "Using GCS bucket (default): $GCS_BUCKET"

# --- Application Default Credentials ---
# If you run 'gcloud auth application-default login', you don't need a key file.
# Uncomment and set GOOGLE_APPLICATION_CREDENTIALS only if using a service account key file.
ADC_PATH=""
if [ -n "$GOOGLE_APPLICATION_CREDENTIALS" ] && [ -f "$GOOGLE_APPLICATION_CREDENTIALS" ]; then
  ADC_PATH="$GOOGLE_APPLICATION_CREDENTIALS"
else
  # Well-known path for gcloud auth application-default login
  if [ "$(uname)" = "Darwin" ]; then
    ADC_DEFAULT="$HOME/Library/Application Support/gcloud/application_default_credentials.json"
  else
    ADC_DEFAULT="$HOME/.config/gcloud/application_default_credentials.json"
  fi
  if [ -f "$ADC_DEFAULT" ]; then
    ADC_PATH="$ADC_DEFAULT"
  fi
fi

# --- Firebase web config (optional) ---
FIREBASE_API_KEY=""
FIREBASE_AUTH_DOMAIN="${PROJECT_ID}.firebaseapp.com"

if command -v firebase &>/dev/null; then
  (firebase use "$PROJECT_ID" 2>/dev/null || true)
  # Try to get first web app SDK config (appId can be in "appId" or "app_id" in JSON)
  WEB_APP_ID=$(firebase apps:list 2>/dev/null | awk '/web/{getline; print $1}' | head -1)
  [ -z "$WEB_APP_ID" ] && WEB_APP_ID=$(firebase apps:list --json 2>/dev/null | sed -n 's/.*"appId"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
  if [ -n "$WEB_APP_ID" ]; then
    CONFIG=$(firebase apps:sdkconfig web "$WEB_APP_ID" 2>/dev/null || true)
    if [ -n "$CONFIG" ]; then
      FIREBASE_API_KEY=$(echo "$CONFIG" | sed -n 's/.*"apiKey"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
      FIREBASE_AUTH_DOMAIN=$(echo "$CONFIG" | sed -n 's/.*"authDomain"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
    fi
  fi
  [ -z "$FIREBASE_AUTH_DOMAIN" ] && FIREBASE_AUTH_DOMAIN="${PROJECT_ID}.firebaseapp.com"
fi

if [ -z "$FIREBASE_API_KEY" ]; then
  echo "Firebase: could not get API key from CLI. Add a web app in Firebase Console and run 'firebase use $PROJECT_ID', or set NEXT_PUBLIC_FIREBASE_API_KEY in .env manually."
fi

# --- Write .env ---
cat > "$ENV_FILE" << EOF
# Generated by scripts/generate-env.sh — values from gcloud / Firebase CLI

# --- GCP ---
GCP_PROJECT_ID=$PROJECT_ID
GCS_BUCKET_NAME=$GCS_BUCKET

# Use Application Default Credentials (gcloud auth application-default login).
# Or set this to a service account key path for server/CI.
EOF

if [ -n "$ADC_PATH" ]; then
  echo "GOOGLE_APPLICATION_CREDENTIALS=$ADC_PATH" >> "$ENV_FILE"
else
  echo "# GOOGLE_APPLICATION_CREDENTIALS=/path/to/service-account-key.json" >> "$ENV_FILE"
  echo "# Run: gcloud auth application-default login" >> "$ENV_FILE"
fi

cat >> "$ENV_FILE" << EOF

# --- Firebase (client-side admin login) ---
NEXT_PUBLIC_FIREBASE_PROJECT_ID=$PROJECT_ID
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN
NEXT_PUBLIC_FIREBASE_API_KEY=${FIREBASE_API_KEY:-$EXISTING_API_KEY}
EOF

echo ""
echo "Wrote: $ENV_FILE"
echo ""
echo "Next steps:"
if [ -z "$ADC_PATH" ]; then
  echo "  1. Run: gcloud auth application-default login"
fi
if [ -z "$FIREBASE_API_KEY" ] && [ -z "$EXISTING_API_KEY" ]; then
  echo "  2. In Firebase Console → Project settings → General, copy 'Web API Key' into .env as NEXT_PUBLIC_FIREBASE_API_KEY"
fi
echo "  3. Create admin user in Firebase Auth and run: node scripts/set-admin.js <email>"
echo "  4. npm run dev"
